### ISSUE TITLE
Build out homepage components

### ISSUE THREAD

**Issue by aeksco** [rcos/observatory-client#1]
@Frankie-guz See attached:

<img width="613" alt="main_home_components" src="https://user-images.githubusercontent.com/4616233/32144700-6cc0ab66-bc93-11e7-8306-d402eb184bca.png">

Don't worry about dynamic content or the header/body/button variants for the three Developers/Projects/Achievements components - we'll square those details away later. Just think in broad strokes with the HTML and apply some of the Bootstrap styles and column rules we were going over yesterday

**Comment by Frankie-guz** [comment]
How does this look for the Achievements page:
![achievements page](https://user-images.githubusercontent.com/31551878/32401841-df8b764a-c0ed-11e7-8760-353da70c383d.png)

**Comment by aeksco** [comment]
@Frankie-guz Looks great - make another Issue detailing the components required for the Achievements page

**Comment by aeksco** [comment]
Marked as resolved
