### ISSUE TITLE
Button click handlers

### ISSUE THREAD

**Issue by Frankie-guz** [rcos/observatory-client#22]
Run through the temporary site adding click handlers on buttons. Starting first with linking up using the router. For example:
![screen shot 2017-12-09 at 1 37 02 pm](https://user-images.githubusercontent.com/31551878/33798445-31ec013e-dce6-11e7-851c-d10b14ff9b21.png)

**Comment by Frankie-guz** [comment]
Opened PR

**Comment by aeksco** [comment]
Resolved
