### ISSUE TITLE
Documentation for new Observatory dev team next semester

### ISSUE THREAD

**Issue by Frankie-guz** [rcos/observatory-client#23]
Make a list including basic knowledge require and a start-up guide for next semester's dev team learning Vue
![screen shot 2017-12-09 at 1 40 02 pm](https://user-images.githubusercontent.com/31551878/33798470-9fb235bc-dce6-11e7-83a7-7fbd0419c396.png)

**Comment by Frankie-guz** [comment]
Pretty much done--planning on merging with README.
https://docs.google.com/document/d/1VWkWGGE--rNOxzt4jardGt69sv-5aeHV1JR7Ksd81qE/edit?usp=sharing

**Comment by aeksco** [comment]
Merged - closing this issue.
