### ISSUE TITLE
Registration Form UI Enhancements

### ISSUE THREAD

**Issue by aeksco** [rcos/observatory-client#86]
- Remove default values from User Registration form. Remove default values for `register_user` in the `observatory-client/src/store/auth/state.js` file

- Remove hardcoded `Successfully Regisetered!` message at the bottom of the `<template>` tag defined in `observatory-client/src/containers/auth_register/components/layout.vue`

- Replace the `<FormSubmit ... />` component in the `<template>` tag with the following line:

```
<FormSubmit label='Sign Up' class='btn-success btn-block w-100'/>
```

**Comment by chengstark** [comment]
86 finished

**Comment by aeksco** [comment]
Resolved
